spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: jbbfqsgvtbkytq
    password: 91442aca5794dc7343ac369dc1244e69726b80067881926980e768d49d500976
    url: jdbc:postgresql://ec2-54-157-16-196.compute-1.amazonaws.com:5432/d2tkrs5fjfvip9
  sql:
    init:
      plataform: postgres
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
